<p><header id="header" role="banner"><br>
  <a id="skip-link" href="#main-menu">Jump to navigation</a><br>
  <div id="stinson"></p>
<p><!--<br>
<a id="blocki" href="http://illinois.edu" title="University of Illinois home"><img src="/new/images/brand_blocki.png" alt="Illinois Block I logo" /></a></p>
<p>--><br>
  <h1><a href="/" title="mstinson.github.io">Mark Stinson</a></h1><br>
  <h2>Creative visual communications</h2><br>
  </div><!-- /end #stinson --><br> 
  </header>
</p>
<!doctype html>
<html>
<head>
<meta charset="UTF-8">
<title>Untitled Document</title>
</head>

<body>
</body>
</html>
